import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";

import { CompactPhotocard } from "../components/photocard";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();
  const loggedIn = sessionData != null;

  // TODO: get this from the DB
  const cards = [
    {
      id: "123ABCD",
      name: "Suga",
      group: "BTS",
      album: "Love Yourself",
      pcImageUrl: "https://data.whicdn.com/images/318419844/original.jpg",
    },
    {
      id: "123ABCD",
      name: "Suga",
      group: "BTS",
      album: "Love Yourself",
      pcImageUrl: "https://data.whicdn.com/images/318419844/original.jpg",
    },
    {
      id: "123ABCD",
      name: "Suga",
      group: "BTS",
      album: "Love Yourself",
      pcImageUrl: "https://data.whicdn.com/images/318419844/original.jpg",
    },
    {
      id: "123ABCD",
      name: "Suga",
      group: "BTS",
      album: "Love Yourself",
      pcImageUrl: "https://data.whicdn.com/images/318419844/original.jpg",
    },
    {
      id: "123ABCD",
      name: "Suga",
      group: "BTS",
      album: "Love Yourself",
      pcImageUrl: "https://data.whicdn.com/images/318419844/original.jpg",
    },
    {
      id: "123ABCD",
      name: "Suga",
      group: "BTS",
      album: "Love Yourself",
      pcImageUrl: "https://data.whicdn.com/images/318419844/original.jpg",
    }
  ]

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <Greeting name={sessionData?.user?.name} visible={loggedIn} />
        <div className="mt-3 grid gap-5 pt-3 text-center md:grid-cols-3 lg:w-2/3">
          {
            !loggedIn ?
              <p>Please log in!</p> :
              cards.map(({ name, group, album, pcImageUrl, id }) =>
                <CompactPhotocard
                  key={id}
                  name={name}
                  artist={group}
                  album={album}
                  pcImageUrl={pcImageUrl}
                  id={id}
                />
              )
          }
        </div>
      </main>
    </>
  );
};

const Greeting: React.FC<{ name: string | null | undefined, visible: boolean }> = ({ name, visible }) => {
  return (
    <>
      {visible ? <p>Hello, {name ?? "Friend"}!</p> : null}
    </>
  );
}

export default Home;
