import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import { CompactPhotocard } from "../components/photocard";
import { Navbar } from "../components/layout/navbar";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  // TODO: get this from the DB
  const cards = [
    {
      id: "123ABCD",
      name: "Suga",
      group: "BTS",
      album: "Love Yourself",
      pcImageUrl: "https://data.whicdn.com/images/318419844/original.jpg",
    },
    {
      id: "123ABCD",
      name: "Suga",
      group: "BTS",
      album: "Love Yourself",
      pcImageUrl: "https://data.whicdn.com/images/318419844/original.jpg",
    },
    {
      id: "123ABCD",
      name: "Suga",
      group: "BTS",
      album: "Love Yourself",
      pcImageUrl: "https://data.whicdn.com/images/318419844/original.jpg",
    },
    {
      id: "123ABCD",
      name: "Suga",
      group: "BTS",
      album: "Love Yourself",
      pcImageUrl: "https://data.whicdn.com/images/318419844/original.jpg",
    },
    {
      id: "123ABCD",
      name: "Suga",
      group: "BTS",
      album: "Love Yourself",
      pcImageUrl: "https://data.whicdn.com/images/318419844/original.jpg",
    },
    {
      id: "123ABCD",
      name: "Suga",
      group: "BTS",
      album: "Love Yourself",
      pcImageUrl: "https://data.whicdn.com/images/318419844/original.jpg",
    }
  ]

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <div className="mt-3 grid gap-5 pt-3 text-center md:grid-cols-3 lg:w-2/3">
          {
            cards.map(({ name, group, album, pcImageUrl, id }) =>
              <CompactPhotocard
                key={id}
                name={name}
                artist={group}
                album={album}
                pcImageUrl={pcImageUrl}
                id={id}
              />
            )
          }
        </div>
        {/* <AuthShowcase /> */}
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery();

  const { data: sessionData } = useSession();

  console.log("session: ", sessionData);

  return (
    <div className="flex flex-col items-center justify-center gap-2">
      {sessionData && (
        <p className="text-2xl text-blue-500">
          Logged in as {sessionData?.user?.name}
        </p>
      )}
      {secretMessage && (
        <p className="text-2xl text-blue-500">{secretMessage}</p>
      )}
      <button
        className="rounded-md border border-black bg-violet-50 px-4 py-2 text-xl shadow-lg hover:bg-violet-100"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
